### PR TITLE
template updates

### PR DESCRIPTION
**Pull request by mugshepherd**
## Changes
- updated _template2.
- updated persons 3&4
- created person 5
- updated pet/test2.html

this has been deployed at [address](address)

### CODE REVIEW

**Comment by mugshepherd** [comment]
@bayramcura - let's discuss

**Comment by bayramcura** [comment]
Lets discuss
@mugshepherd

**Review by bayramcura — CHANGES_REQUESTED** [review]
Toby there are significant changes and please pull the latest changes and please generate a template for French rather than overwriting.

**Comment by bayramcura** [comment]
Toby we need this pull request to go to TEST and not DEVELOP
Toby please pull the latest changes from DEVELOP and make the new pull request, please.
I am therefore closing this PR.

**Pull request closed without merging**
